# action.yml
name: Semver - Get New Tag Version to release
description: Check the last tag version released on Github and get the next version to release
inputs:
  repo_token:
    description: The GitHub token to use for authentication
    required: true

outputs:
  next_version:
    description: The next version to be released

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_token }}


branding:
  icon: arrow-up-circle
  color: purple